# Generated by Django 5.1.6 on 2025-02-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0002_employee_shift_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='matricula',
            field=models.CharField(default=1123456, max_length=20),
            preserve_default=False,
        ),
    ]
