# Generated by Django 5.1.6 on 2025-02-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0003_employee_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('P', 'Presença'), ('F', 'Falta'), ('AT', 'Atestado/Declaração'), ('AF', 'Afastado'), ('Férias', 'Férias')], max_length=6),
        ),
    ]
