# Generated by Django 5.1.6 on 2025-02-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0004_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('P', 'Presença'), ('F', 'Falta'), ('A', 'Atestado'), ('N', 'Não Registrado')], max_length=1),
        ),
    ]
