# Generated by Django 5.1.6 on 2025-02-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle', '0005_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('P', 'Presença'), ('F', 'Falta'), ('AT', 'Atestado'), ('AF', 'Atestado'), ('FE', 'ferias')], max_length=2),
        ),
    ]
